version: 2
updates:
    # Maintain dependencies for the project
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
    - package-ecosystem: "bundler"
      directory: "/"
      schedule:
        interval: "daily"