plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'config.ru'

# Relax some cops for Rails conventions
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'test/**/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

# Disable cops that are not critical for this demo app
Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
